server:
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:postgresql://host:port/db
    username: postgres
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
recaptcha:
  secret: getOneFromGoogle