server:
  servlet:
    context-path: /api

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  cache:
    type: redis

  redis:
    host: ${SPRING_REDIS_HOST:localhost}
    port: ${SPRING_REDIS_PORT:6379} 

recaptcha:
  secret: ${RECAPTCHA_SECRET}
